name: DockerImage Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: xinrea/xobs-scene-server

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go environment
      uses: actions/setup-go@v3.0.0
    - name: Test
      run: go test ./...
    - name: Go Build
      run: |
        go build -o xobs-scene-server main.go
    - name: Prepare Docker
      uses: docker/login-action@v1.14.1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Check builds
      run: ls -al
    - name: Build the Docker image
      uses: docker/build-push-action@v2.10.0
      with:
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        
